---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-mirage-dev-v1alpha1-previewenvironment
  failurePolicy: Fail
  name: vpreviewenvironment-v1alpha1.kb.io
  rules:
  - apiGroups:
    - mirage.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - previewenvironments
  sideEffects: None
