{{- if and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "mirage.fullname" . }}-controller-manager-metrics-monitor
  namespace: {{ include "mirage.namespace" . }}
  labels:
    {{- include "mirage.labels" . | nindent 4 }}
    {{- with .Values.metrics.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  endpoints:
    - path: /metrics
      port: https
      scheme: https
      interval: {{ .Values.metrics.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.metrics.serviceMonitor.scrapeTimeout }}
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      tlsConfig:
        insecureSkipVerify: {{ .Values.metrics.serviceMonitor.insecureSkipVerify }}
  selector:
    matchLabels:
      {{- include "mirage.selectorLabels" . | nindent 6 }}
{{- end }}
